const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const source=fs.readFileSync('web/projects.js','utf8');
function harness(){
 const elements=new Map(),storage=new Map(),requests=[],remote=new Map();let supported=true;
 class Element{constructor(id=''){this.id=id;this.textContent='';this.dataset={};this.children=[];this.hidden=false;this.open=false;this.onclick=()=>{};this.value='';}set innerHTML(text){for(const m of text.matchAll(/id="([^"]+)"/g))elements.set(m[1],new Element(m[1]));}get innerHTML(){return'';}setAttribute(){}append(...els){this.children.push(...els);}appendChild(el){this.children.push(el);if(el.id)elements.set(el.id,el);}replaceChildren(){this.children=[];}showModal(){this.open=true;}close(){this.open=false;}}
 const el=id=>{if(!elements.has(id))elements.set(id,new Element(id));return elements.get(id);};
 const context={console,Blob,Headers,URL,AbortController,crypto:webcrypto,Uint8Array,Date,JSON,Promise,Map,Set,Number,String,Array,Error,RegExp,Math,requests,remote,navigator:{onLine:true},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{createElement:()=>new Element(),body:new Element(),addEventListener:()=>{},visibilityState:'visible'},window:{addEventListener:()=>{}},setTimeout:()=>1,clearTimeout:()=>{},setInterval:()=>1,$:el,state:{title:'Test board',nodes:[],edges:[],settings:{},view:{},mainPrompt:'Task',consoleSession:null},cloudConfig:{kind:'private-pc',backendUrl:'https://desktop.test.ts.net'},cloudAuth:{accessToken:'a'.repeat(32)},validCloudConfig:x=>/^https:\/\/[a-z.]+\.ts\.net$/.test(x.backendUrl)?x:null,withoutVideoPayloads:x=>x,snapshot:()=>JSON.parse(JSON.stringify(context.state)),markDirty:()=>{context.dirty=true;},validateProject:async raw=>{const {projectCloud,...out}=raw;return out;},dirty:false,busy:false,ioBusy:false,history:[],future:[],selected:null,selectedMark:null,selectedEdge:null,pending:null,action:null,cancelTranscriptionQueue(){},consoleRefreshProject(){},resumeYouTubeImports(){},scheduleTranscriptionQueue(){},renderAll(){},updateRefreshNotice(){},R:{clearImageCache(){}},saveProject(){},openProject:async()=>{},confirm:()=>true,toast:()=>{},cloudFetch:async(path,opts={})=>{
  requests.push({path,opts});if(path==='/health')return new Response(JSON.stringify({capabilities:{persistentProjects:supported,projectRevision:supported}}));
  const id=path.split('/')[2],saved=remote.get(id),key=new Headers(opts.headers).get('X-Vision-Project-Key');
  if(saved&&key!==saved.key)return new Response(JSON.stringify({error:'bad key'}),{status:403});
  if(opts.method==='PUT'){const data=JSON.parse(opts.body);if(data.revision!==(saved?.revision||0))return new Response(JSON.stringify({error:'newer copy'}),{status:409});const record={...data,key,revision:data.revision+1};remote.set(id,record);return new Response(JSON.stringify({revision:record.revision}));}
  return new Response(JSON.stringify(saved||{error:'missing'}),{status:saved?200:404});
 }};
 vm.createContext(context);vm.runInContext(source,context);return{context,el,requests,remote,storage,run:code=>vm.runInContext(code,context),setSupported:v=>supported=v};
}
(async()=>{
 const h=harness();await Promise.resolve();assert.equal(h.requests.length,0,'empty boot must not save');assert.equal(h.context.state.projectCloud,undefined);
 h.run('markDirty()');const initial={...h.context.state.projectCloud};assert.equal(initial.id.length>16,true);assert.equal(initial.key.length,64);h.context.state.title='Renamed board';h.run('markDirty()');assert.equal(h.context.state.projectCloud.id,initial.id,'renames retain identity');
 await h.run('flushProjectSave()');assert.equal(h.context.state.projectCloud.revision,1);assert.equal(h.remote.get(initial.id).project.title,'Renamed board');assert.equal(h.remote.get(initial.id).key,initial.key);assert.equal(h.context.dirty,false);
 const exported=await h.run('validateProject(projectSnapshot())');assert.equal(exported.projectCloud.id,initial.id,'editable project retains keyholder');assert.equal(exported.projectCloud.key,initial.key);
 const sanitized=await h.run('validateProject({...projectSnapshot(),projectCloud:{id:"bad",key:"bad",backendUrl:"http://evil.test"}})');assert.equal(sanitized.projectCloud,undefined);
 const before=h.remote.get(initial.id);before.revision++;h.context.state.title='Unsynced local title';h.run('markDirty()');await assert.rejects(h.run('flushProjectSave()'),/newer copy/);assert.equal(h.run('projectConflict'),true);assert.equal(h.remote.get(initial.id).project.title,'Renamed board','409 preserves PC content');assert.equal(h.context.state.title,'Unsynced local title','409 preserves local content');
 await h.run('projectFork()');assert.notEqual(h.context.state.projectCloud.id,initial.id);assert.notEqual(h.context.state.projectCloud.key,initial.key);assert.equal(h.remote.get(initial.id).project.title,'Renamed board');assert.equal(h.remote.get(h.context.state.projectCloud.id).project.title,'Unsynced local title');
 await assert.rejects(h.run('projectRequest("/projects/project-another-id/runs")'),/active project changed/);
 const old=harness();old.setSupported(false);old.run('markDirty()');await assert.rejects(old.run('flushProjectSave()'),/Update PC processor/);assert.equal(old.requests.filter(r=>r.opts.method==='PUT').length,0);assert.match(old.el('saveState').textContent,/Update PC processor/);assert.ok([...old.storage.keys()].some(k=>k.startsWith('vision-projects-v1:')),'old server keeps browser backup');
 const conflict=harness();conflict.run('markDirty()');await conflict.run('flushProjectSave()');const id=conflict.context.state.projectCloud.id;conflict.remote.get(id).revision++;conflict.remote.get(id).project.title='Other device';conflict.context.state.title='Local';conflict.run('markDirty()');await conflict.run('projectReconcile()');assert.equal(conflict.context.state.title,'Local');assert.equal(conflict.run('projectConflict'),true);await conflict.run('projectReconcile({force:true})');assert.equal(conflict.context.state.title,'Other device');assert.equal(conflict.context.state.projectCloud.revision,2);
 const base=fs.readFileSync('web/base.js','utf8'),exportCode=base.slice(base.indexOf('async function buildExportFiles('),base.indexOf('async function readProjectInput('));assert.doesNotMatch(exportCode,/JSON\.stringify\(archive\)|projectCloud|\.vision\.json/,'AI package does not emit editable project or project secret');
 console.log('Project smoke: blank boot, identity, revision saves, portable metadata, safe conflicts, fork, origin/ID isolation, old-server fallback, latest PC recovery, and export-secret isolation passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
