/* Optional local sound detection: real queue/serialization helpers, mocked processing only. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const base=fs.readFileSync('web/base.js','utf8'),cloud=fs.readFileSync('web/cloud.js','utf8'),video=fs.readFileSync('web/video-preview.js','utf8');
const slice=(s,a,b)=>s.slice(s.indexOf(a),s.indexOf(b,s.indexOf(a)));
const queue=slice(base,'// Durable, sequential ASR:','async function runTranscription(');
const makeSection=(start=0,end=10)=>({start,end,mimeType:'audio/mpeg',audioData:'data:audio/mpeg;base64,YQ==',text:null,done:false});
function fixture(includeSoundEvents=true,kind='audio'){
 const source={id:'source',name:kind==='video'?'sample.mp4':'sample.wav',mime:kind==='video'?'video/mp4':'audio/wav',data:'data:audio/wav;base64,YQ==',audioOffsetFromVideo:2,transcriptToPrompt:true};
 const job={id:'job-12345678',sourceId:source.id,sourceName:source.name,sourceKind:kind,provider:'local',includeSoundEvents,offsetSeconds:2,sections:[makeSection()],status:'waiting'};
 const node={id:'node',attachments:[source],transcriptionJobs:[job]},state={settings:{transcriptionProvider:'local',includeSoundEvents},nodes:[node],projectCloud:{id:'project-1234567890',backendUrl:'https://server.test'}};
 const calls=[],messages=[],activities=[],stats={released:0,paid:0},control={soundReady:true,result:null};let serial=0;
 const ctx={state,history:[],future:[],selected:null,busy:false,ioBusy:false,navigator:{onLine:true},cloudConfig:{backendUrl:'https://server.test'},sessionApiKey:null,AbortController,Blob,DOMException,TextEncoder,Date,Math,Number,String,Set,Map,URL,JSON,TypeError,
 window:{JEWTranscription:{MAX_INLINE_BYTES:14000000,requestAudio:async()=>{stats.paid++;throw new Error('Unexpected paid request');}},JEWSections:{boundaries:analysis=>[{start:0,end:analysis.duration}]}},
 $:()=>null,uid:()=>`id-${++serial}`,checkpoint(){},markDirty(){},refreshNodeAttachments(){},renderAttachments(){},updateSequence(){},toast:(text,error)=>messages.push({text,error}),recordActivity:(title,text)=>activities.push({title,text}),videoFile:a=>a.mime==='video/mp4',textDataURL:text=>'data:text/plain;base64,'+Buffer.from(text).toString('base64'),readFile:async()=> 'data:audio/mpeg;base64,YQ==',releaseCompletedSourceAudio:()=>stats.released++,applyImportedTranscript:(n,s,text)=>n.prompt=text,videoTranscriptClock:(text,offset)=>text.replace(/\[(\d\d):(\d\d):(\d\d)\.(\d\d\d)\]/g,(m,h,min,sec,ms)=>'['+vm.runInContext(`soundSrtTime(${+h*3600+ +min*60+ +sec+ +ms/1000+offset})`,ctx).replace(',','.')+']'),
 projectCapabilities:async()=>({capabilities:{localTranscription:true},localTranscription:{ready:true},localSoundEvents:{available:control.soundReady,ready:control.soundReady}}),ensureRemoteProject:async()=>state.projectCloud,projectBackup:async()=>{},projectRequest:async(path,options)=>{calls.push({path,options});return options.method==='POST'?{id:'remote-12345',status:'queued'}:control.result;},projectResponse:async data=>data,setTimeout:()=>0,clearTimeout(){},normalizeYouTubeURL:value=>value,validCloudConfig:value=>value,PC_VIDEO_PREVIEW_LIMIT:134217728};
 vm.createContext(ctx);vm.runInContext(queue+'\n'+base.slice(base.indexOf('function saveTranscript(')).split('\n')[0]+'\n'+slice(base,'function storeVideoTranscript(','async function processVideoFile(')+'\n'+slice(cloud,'function normalizeYouTubeImports(','async function youtubeAPI(')+'\n'+slice(video,'function normalizePCVideo(','function pcVideoCurrent('),ctx);
 // storeVideoTranscript's UI helper is outside the extracted slice.
 ctx.updateVideoAttachments=()=>{};
 const run=code=>vm.runInContext(code,ctx);ctx.rawJob=job;ctx.rawSource=source;
 return{ctx,state,node,job,source,calls,messages,activities,stats,control,run,pump:()=>run('pumpTranscriptionQueue()'),due:()=>job.nextAttemptAt=0};
}
const success={sections:[{start:0,end:10,text:'[00:00:01.000] Hello.\n[00:00:03.000] *Cat meows*'}],speechText:'[00:00:01.000] Hello.',speechSegments:[{start:1,end:2,text:'Hello.'}],soundEvents:[{start:3,end:4,label:'Meow',score:.91}],soundEventStatus:'completed',warnings:[],combinedSrt:'1\n00:00:01,000 --> 00:00:02,000\nHello.\n\n2\n00:00:03,000 --> 00:00:04,000\n*Cat meows*\n'};
(async()=>{
 // The opt-in survives project queue restoration, and does not opt legacy jobs in.
 let f=fixture();assert.equal(f.run('validateTranscriptionJobs([rawJob],[rawSource])[0].includeSoundEvents'),true);delete f.job.includeSoundEvents;assert.equal(f.run('validateTranscriptionJobs([rawJob],[rawSource])[0].includeSoundEvents'),false);f.job.includeSoundEvents='true';assert.equal(f.run('validateTranscriptionJobs([rawJob],[rawSource])[0].includeSoundEvents'),false);
 f=fixture();f.ctx.youtubeRaw=[{url:'https://youtu.be/abcdefghijk',clientRequestId:'youtube-123456',backendUrl:'https://server.test',targetId:'node',sourceId:'source',provider:'local',includeSoundEvents:true}];assert.equal(f.run('normalizeYouTubeImports(youtubeRaw)[0].includeSoundEvents'),true);f.ctx.youtubeRaw[0].provider='gemini';assert.equal(f.run('normalizeYouTubeImports(youtubeRaw)[0].includeSoundEvents'),false);
 f.ctx.mediaRaw={requestId:'media-12345678',projectId:'project-1234567890',backendUrl:'https://server.test',provider:'local',includeSoundEvents:true};assert.equal(f.run('normalizePCVideo(mediaRaw).includeSoundEvents'),true);
 // Setup failures retain audio and never call a paid provider.
 f=fixture();f.control.soundReady=false;await f.pump();assert.match(f.job.error,/InstallSoundEvents/);assert.equal(f.calls.length,0);assert.equal(f.stats.paid,0);assert.ok(f.job.sections[0].audioData);
 // Requested results keep speech and sounds, align SRT to video once, and retain uncertainty metadata.
 f=fixture(true,'video');await f.pump();assert.equal(JSON.parse(f.calls[0].options.body).includeSoundEvents,true);f.control.result={status:'complete',result:success};f.due();await f.pump();assert.equal(f.node.transcriptionJobs.length,0);assert.equal(f.node.prompt,success.speechText);const txt=f.node.attachments.find(a=>a.transcriptOf),srt=f.node.attachments.find(a=>a.subtitleOf);assert.equal(srt.mime,'application/x-subrip');assert.equal(srt.name,'sample.srt');assert.equal(srt.status,'complete');assert.match(Buffer.from(srt.data.split(',')[1],'base64').toString(),/00:00:05,000 --> 00:00:06,000\n\*Cat meows\*/);assert.match(Buffer.from(txt.data.split(',')[1],'base64').toString(),/Sound labels are AI estimates/);assert.equal(f.stats.paid,0);
 // Optional sound failure still stores complete speech, with visible warnings and partial subtitles.
 f=fixture();await f.pump();f.control.result={status:'complete',result:{...success,sections:[{start:0,end:10,text:'[00:00:01.000] Hello.'}],soundEvents:[],soundEventStatus:'failed',warnings:['Sound detection stopped; speech retained.'],combinedSrt:'1\n00:00:01,000 --> 00:00:02,000\nHello.\n'}};f.due();await f.pump();assert.equal(f.node.attachments.find(a=>a.transcriptOf).status,'complete');assert.equal(f.node.attachments.find(a=>a.subtitleOf).status,'partial');assert.match(f.messages.at(-1).text,/speech retained/);assert.equal(f.messages.at(-1).error,true);assert.match(f.activities.at(-1).text,/speech retained/);
 // Invalid sound output cannot discard the compressed source or claim completion.
 f=fixture();await f.pump();f.control.result={status:'complete',result:{...success,soundEvents:[{start:0,end:1000,label:'Meow',score:.9}]}};f.due();await f.pump();assert.equal(f.job.status,'error');assert.ok(f.job.sections[0].audioData);assert.equal(f.stats.released,0);
 // Empty sound track is valid; negative video offsets clip only SRT's unsupported pre-zero time.
 f=fixture();f.ctx.subtitle=success.combinedSrt;assert.match(f.run('offsetSoundSrt(subtitle,-1.5,0,10)'),/00:00:00,000 --> 00:00:00,500/);assert.equal(f.run('offsetSoundSrt("",2,0,10)'), '');assert.throws(()=>f.run('offsetSoundSrt("not subtitles",0,0,10)'),/invalid subtitles/);
 // Opt-in is frozen at preparation call, including while the decoder is still loading audio.
 f=fixture();f.node.transcriptionJobs=[];let release;f.ctx.file={};f.ctx.signal=new AbortController().signal;f.ctx.decoder={request:async type=>type==='analyze'?await new Promise(resolve=>release=resolve):{audio:new Uint8Array([1]),mimeType:'audio/mpeg'}};const preparing=f.run('prepareTranscriptionQueue(state.nodes[0],rawSource,file,decoder,signal)');f.state.settings.includeSoundEvents=false;f.state.settings.transcriptionProvider='gemini';release({duration:10});await preparing;assert.equal(f.node.transcriptionJobs[0].includeSoundEvents,true);assert.equal(f.node.transcriptionJobs[0].provider,'local');
 console.log('PASS: sound opt-in/queue/media/YouTube persistence; setup and no-paid-fallback; complete/failure results; speech retention; subtitle timing and validation; frozen asynchronous preference.');
})().catch(error=>{console.error(error);process.exitCode=1;});
