/* Vision Venture. Account-owned UI state is deliberately separate from the board.
 * The server owns accepted work. This view only submits once and reconciles IDs.
 */
const VENTURE_DEFAULTS={model:'gpt-5.6-terra',maxOutputTokens:16000,memoryEnabled:false,runOptions:{mode:'auto',effort:'auto',verbosity:'auto',webSearch:false,codeInterpreter:true}};
const VENTURE_TERMINAL=new Set(['completed','incomplete','cancelled','error']);
const VENTURE_ICONS={menu:'M4 6h16M4 12h11M4 18h16',plus:'M12 5v14M5 12h14',arrow:'m6 12 6-6 6 6M12 6v13',back:'m14 6-6 6 6 6',close:'m6 6 12 12M6 18 18 6',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',copy:'M9 9h11v11H9zM15 9V4H4v11h5',retry:'M4 10a8 8 0 1 1 1 8M4 4v6h6',file:'M6 3h8l4 4v14H6zM14 3v5h4',mic:'M9 4a3 3 0 0 1 6 0v8a3 3 0 0 1-6 0zM6 11v1a6 6 0 0 0 12 0v-1M12 18v4M9 22h6',stop:'M6 6h12v12H6z',search:'M10 17a7 7 0 1 0 0-14 7 7 0 0 0 0 14zm5-2 6 6',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4',dots:'M5 12h.01M12 12h.01M19 12h.01',edit:'m15 4 5 5-11 11H4v-5zM12 7l5 5',compass:'m9 9 8-2-2 8-8 2zM12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20'};
function ventureIcon(name){return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="'+(VENTURE_ICONS[name]||VENTURE_ICONS.file)+'"/></svg>';}
function ventureSettings(value){const s={model:typeof value?.model==='string'?value.model:VENTURE_DEFAULTS.model,maxOutputTokens:Number(value?.maxOutputTokens)||16000,runOptions:normalizeRunOptions(value?.runOptions),memoryEnabled:value?.memoryEnabled===true};const p=ventureParameterProfile(s.model);if(!p?.pro)s.runOptions.mode='auto';if(!(p?.efforts||['auto']).includes(s.runOptions.effort))s.runOptions.effort='auto';if(!p?.verbosity)s.runOptions.verbosity='auto';return s;}
function ventureId(){return 'v-'+crypto.randomUUID().replaceAll('-','');}
const venture={uid:'',epoch:0,selection:0,open:false,ready:false,current:null,runs:[],history:[],historyCursor:null,messageCursor:null,cursor:0,settings:ventureSettings(),files:[],drafts:new Map(),pending:null,funding:null,poll:null,polling:false,sending:false,rendered:new Map(),settingsTimer:null,settingsSaving:null,settingsVersion:0,dragging:false,recognition:null,notice:'',historySearchTimer:null};
function ventureActive(run){return !VENTURE_TERMINAL.has(run.status);}
function ventureScope(){return accountSignedIn()?accountFirebase.currentUser.uid:'';}
function ventureStorageKey(kind){return 'vision-venture-'+kind+'-'+encodeURIComponent(venture.uid);}
function ventureRemember(kind,value){try{if(value===null)sessionStorage.removeItem(ventureStorageKey(kind));else sessionStorage.setItem(ventureStorageKey(kind),JSON.stringify(value));}catch{}}
function ventureRecall(kind){try{return JSON.parse(sessionStorage.getItem(ventureStorageKey(kind))||'null');}catch{return null;}}
function ventureError(error){if(error?.name==='AbortError')return 'Connection timed out. Your accepted work is still on FUPCJ Server.';return error?.message||'Venture could not connect. Check FUPCJ Server.';}
async function ventureFetch(path,options={}){
 const {timeoutMs,...fetchOptions}=options;const epoch=venture.epoch,controller=new AbortController(),parentSignal=options.signal;const abort=()=>controller.abort();if(parentSignal?.aborted)abort();else parentSignal?.addEventListener('abort',abort,{once:true});const timer=setTimeout(()=>controller.abort(),Number.isFinite(timeoutMs)?Math.max(1000,Math.min(720000,timeoutMs)):options.body instanceof FormData?180000:20000);
 try{const response=await cloudFetch(path,{...fetchOptions,signal:controller.signal});if(epoch!==venture.epoch)throw new DOMException('Account changed','AbortError');await consoleCheckedResponse(response);return response;}finally{clearTimeout(timer);parentSignal?.removeEventListener('abort',abort);}
}
async function ventureJSON(path,method='GET',body){const response=await ventureFetch(path,{method,...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});return response.json();}
function venturePath(cid=venture.current?.id){if(!cid)throw new Error('Start a venture first.');return '/venture/conversations/'+encodeURIComponent(cid);}
function ventureRunPath(cid=venture.current?.id){if(!cid)throw new Error('Start a venture first.');return '/projects/'+encodeURIComponent(cid)+'/runs';}
function ventureSetNotice(message){venture.notice=message||'';$('ventureNotice').textContent=venture.notice;$('ventureNotice').hidden=!venture.notice;}
function ventureInstall(){
 const root=document.createElement('section');root.id='visionVenture';root.className='venture-root';root.hidden=true;root.setAttribute('aria-label','Venture');
 root.innerHTML=`<button class="venture-scrim" id="ventureScrim" aria-label="Close conversation history" hidden></button>
 <aside class="venture-sidebar" id="ventureSidebar" aria-label="Conversation history"><div class="venture-sidebar-top"><span class="venture-wordmark">${ventureBrandIcon()}<b>Venture</b></span><button class="v-icon venture-mobile-close" id="ventureHistoryClose" aria-label="Close history">${ventureIcon('close')}</button></div>
 <button class="venture-new" id="ventureNew">${ventureIcon('plus')} New venture <span>↗</span></button>
 <label class="venture-search">${ventureIcon('search')}<input id="ventureSearch" type="search" placeholder="Search conversations" aria-label="Search conversation titles" maxlength="150"></label>
 <div class="venture-history-label">YOUR VENTURES</div><nav id="ventureHistory" class="venture-history" aria-label="Saved ventures"></nav><button id="ventureMoreHistory" class="v-text-button" hidden>Load more conversations</button>
 <div class="venture-sidebar-foot"><span class="venture-server-dot"></span><span>Saved on FUPCJ Server<small>Your conversations. Your files.</small></span></div></aside>
 <div class="venture-main"><header class="venture-header"><button class="v-icon" id="ventureHistoryToggle" aria-label="Toggle conversation history" aria-controls="ventureSidebar" aria-expanded="true">${ventureIcon('menu')}</button>
 <div class="venture-heading"><strong id="ventureTitle">Venture</strong><button class="venture-model-button" id="ventureSettingsToggle" aria-haspopup="dialog" aria-controls="ventureSettings" aria-expanded="false"><span id="ventureModelLabel">Terra</span><span aria-hidden="true">⌄</span></button></div>
 <button class="v-icon" id="ventureNewCompact" aria-label="New venture" title="New venture">${ventureIcon('plus')}</button><button class="venture-board-return" id="ventureBack">${ventureIcon('back')}<span>Board</span></button><button class="venture-avatar" id="ventureAvatar" aria-label="Open account and API funding" aria-haspopup="dialog" aria-expanded="false">V</button></header>
 <div id="ventureNotice" class="venture-notice" role="status" hidden></div>
 <main class="venture-transcript" id="ventureTranscript" tabindex="0" aria-label="Conversation"><button class="v-text-button" id="ventureOlder" hidden>Load earlier messages</button><div id="ventureTurns"></div></main>
 <div class="venture-bottom"><div class="venture-activity" role="status" aria-live="polite"><span id="ventureActivity">Ready when you are.</span><button class="v-text-button" id="ventureCheck" hidden>Check connection</button></div>
 <form id="ventureCompose" class="venture-compose"><div id="ventureAttachments" class="venture-attachments"></div><label for="ventureMessage" class="sr-only">Your message</label><textarea id="ventureMessage" rows="1" maxlength="50000" placeholder="Where will you venture?"></textarea><div id="ventureDictation" class="venture-dictation" hidden><canvas id="ventureWaveform" width="480" height="52" aria-hidden="true"></canvas><span id="ventureDictationStatus" role="status" aria-live="polite"></span><span id="ventureDictationTime" aria-label="Recording time">0:00</span><button type="button" id="ventureDictationSave" hidden>Save audio</button><button type="button" id="ventureDictationOriginal" hidden>Save original audio</button><button type="button" id="ventureDictationSaveText" hidden>Save transcript</button><button type="button" id="ventureDictationDiscard" hidden>Discard recording</button></div>
 <div class="venture-compose-tools"><input type="file" id="ventureFileInput" multiple hidden><button class="v-icon" id="ventureAttach" type="button" aria-label="Attach files" title="Attach files">${ventureIcon('plus')}</button>
 <label class="venture-board-check"><input type="checkbox" id="ventureIncludeBoard">Include board</label><span class="venture-tools-label" id="ventureToolsLabel">Code &amp; files ready</span>
 <button class="v-icon" id="ventureMic" type="button" aria-label="Dictate a message" aria-pressed="false">${ventureIcon('mic')}</button><button class="venture-send" id="ventureSend" type="submit" aria-label="Send message">${ventureIcon('arrow')}</button><button class="venture-send" id="ventureStop" type="button" aria-label="Stop response" hidden>${ventureIcon('stop')}</button></div></form>
 <p class="venture-footnote" id="ventureFootnote">Accepted requests keep working when you leave.</p></div></div>
 <section class="venture-popover venture-settings" id="ventureSettings" role="dialog" aria-label="Venture settings" tabindex="-1" hidden><div class="venture-popover-heading"><strong>Set your course</strong><button class="v-icon" id="ventureSettingsClose" aria-label="Close settings">${ventureIcon('close')}</button></div>
 <label id="ventureModelHeading">Model</label><button type="button" id="ventureModel" class="venture-model-select" aria-haspopup="listbox" aria-controls="ventureModels" aria-expanded="false"></button>
 <div id="ventureModelsPanel" class="venture-models-panel" hidden><div id="ventureModels" role="listbox" aria-labelledby="ventureModelHeading"></div><p class="venture-fine-print" id="ventureModelsStatus"></p><button type="button" id="ventureRefreshModels" class="v-text-button">Refresh models</button></div>
 <label id="ventureProRow" class="venture-pro-toggle"><span>Pro</span><input id="venturePro" type="checkbox" role="switch"><span class="venture-switch-track" aria-hidden="true"></span></label>
 <label class="venture-dial-label" for="ventureEffort">Reasoning effort<output id="ventureEffortValue">Model default</output></label><input type="range" id="ventureEffort" min="0" max="7" step="1"><div class="venture-dial-ends"><span>Default</span><span>Maximum</span></div>
 <label class="venture-dial-label" for="ventureVerbosity">Verbosity<output id="ventureVerbosityValue">Model default</output></label><input type="range" id="ventureVerbosity" min="0" max="3" step="1"><div class="venture-dial-ends"><span>Default</span><span>Detailed</span></div>
 <div class="venture-setting-switches"><label><input type="checkbox" id="ventureWeb">Web search</label><label><input type="checkbox" id="ventureCode" checked>Code &amp; files</label></div>
 <label class="venture-memory-toggle"><input type="checkbox" id="ventureMemory">Use past conversations</label><p class="venture-fine-print">When enabled, relevant excerpts from your other saved conversations can inform this response. Deleted conversations are excluded. This uses additional context tokens.</p>
 <label class="venture-toggle venture-coming-soon" title="Automatic model selection is not enabled in this release"><span>Auto-select model to save tokens<small id="ventureAutoModelHelp">Coming soon</small></span><input id="ventureAutoModel" type="checkbox" role="switch" disabled aria-describedby="ventureAutoModelHelp"></label>
 <label class="venture-dial-label" for="ventureMaxTokens">Output tokens<output id="ventureMaxTokensValue">16,000</output></label><input type="range" id="ventureMaxTokens" min="512" max="128000" step="1"><div class="venture-dial-ends"><span>512</span><span id="ventureMaxTokensEnd">128K</span></div><p class="venture-fine-print">Settings are validated before a request is accepted. Some models may not support every mode or tool. Higher reasoning effort can increase cost and response time.</p><p id="ventureSettingsStatus" class="venture-fine-print" role="status"></p></section>
 <section class="venture-popover venture-account" id="ventureAccount" role="dialog" aria-label="Your account and estimated API funding" tabindex="-1" hidden><div class="venture-popover-heading"><strong id="ventureAccountName">Your account</strong><button class="v-icon" id="ventureAccountClose" aria-label="Close account menu">${ventureIcon('close')}</button></div><p class="venture-account-email" id="ventureAccountEmail"></p><div class="venture-profile-controls"><input type="file" id="ventureAvatarInput" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" hidden><button type="button" id="ventureChooseAvatar" class="v-text-button">Upload profile picture</button><button type="button" id="ventureRemoveAvatar" class="v-text-button" hidden>Use account picture</button></div><p id="ventureAvatarStatus" class="venture-fine-print" role="status">Photos are automatically cropped and compressed.</p><div class="venture-funding-heading"><span>Estimated API balance</span><small id="ventureFundingStatus">Not calibrated</small></div>
 <div class="venture-battery" id="ventureBattery" role="progressbar" aria-label="Estimated API balance" aria-valuemin="0" aria-valuemax="100"><div id="ventureBatteryFill"></div></div><p class="venture-fine-print" id="ventureFundingUpdated">Set a starting balance to activate the meter.</p>
 <div class="venture-funding-actions"><a id="ventureAddFunding" class="venture-fund-link" href="https://platform.openai.com/settings/organization/billing/overview" target="_blank" rel="noopener noreferrer">Add funding ↗</a><button id="ventureCalibrate" class="v-text-button">Set balance</button></div><p id="ventureFundingCoverage" class="venture-fine-print">Tracks Vision activity, not spending elsewhere. This is not OpenAI’s official balance.</p>
 <details class="venture-key-details"><summary>API connection</summary><label for="ventureKey">OpenAI API key</label><input id="ventureKey" type="password" autocomplete="off" spellcheck="false" placeholder="Enter a key to replace the saved connection"><div class="venture-key-actions"><button id="ventureSaveKey">Save key</button><button id="ventureRemoveKey" class="v-text-button">Remove key</button></div><p id="ventureKeyStatus" class="venture-fine-print">Saved keys stay encrypted on FUPCJ Server. Never enter an Admin key here.</p></details>
 <button type="button" id="ventureShowStorage" class="v-text-button">Where are my files saved?</button><div id="ventureStorageDetails" class="venture-fine-print" hidden><code id="ventureStoragePath"></code></div><div class="venture-account-foot"><button id="ventureConnection" class="v-text-button">Processor connection</button><button id="ventureSignOut" class="v-text-button">Sign out</button></div></section>`;
 document.body.appendChild(root);
 const rename=document.createElement('dialog');rename.id='ventureRenameDialog';rename.className='venture-modal';rename.innerHTML='<form id="ventureRenameForm"><h2>Conversation options</h2><label for="ventureRenameValue">Conversation title</label><input id="ventureRenameValue" maxlength="120" required><p id="ventureRenameStatus" class="venture-fine-print" role="status"></p><button type="button" id="ventureDeleteConversation" class="venture-delete-button">Delete conversation</button><div class="dialog-actions"><button type="button" id="ventureRenameCancel">Cancel</button><button type="submit" class="primary">Save</button></div></form>';document.body.appendChild(rename);
 const money=document.createElement('dialog');money.id='ventureBalanceDialog';money.className='venture-modal';money.innerHTML='<form id="ventureBalanceForm"><h2 id="ventureBalanceHeading">Set current balance</h2><p id="ventureBalanceHelp" class="venture-fine-print"></p><label for="ventureBalanceAmount">Amount (USD)</label><input id="ventureBalanceAmount" type="number" inputmode="decimal" min="0" max="1000000" step="0.01" required autocomplete="off"><p id="ventureBalanceStatus" class="venture-fine-print" role="status"></p><div class="dialog-actions"><button type="button" id="ventureBalanceCancel">Cancel</button><button id="ventureBalanceSubmit" type="submit" class="primary">Set balance</button></div></form>';document.body.appendChild(money);
 ventureInstallModels();ventureInstallFunding();
 $('runProjectBtn').childNodes.forEach(node=>{if(node.nodeType===Node.TEXT_NODE&&node.textContent.includes('Run'))node.textContent=node.textContent.replace('Run','Venture');});$('runProjectBtn').innerHTML=ventureBrandIcon()+'<span>Venture</span>';$('runProjectBtn').title='Open Venture';$('runProjectBtn').setAttribute('aria-label','Open Venture');
 $('ventureBack').onclick=ventureClose;$('ventureHistoryToggle').onclick=()=>ventureSidebar(!$('visionVenture').classList.contains('history-open'));$('ventureHistoryClose').onclick=$('ventureScrim').onclick=()=>ventureSidebar(false);
 $('ventureNew').onclick=$('ventureNewCompact').onclick=()=>void ventureNew();$('ventureMoreHistory').onclick=()=>void ventureLoadHistory(true);$('ventureOlder').onclick=()=>void ventureLoadOlder();
 $('ventureSearch').oninput=()=>{clearTimeout(venture.historySearchTimer);venture.historySearchTimer=setTimeout(()=>void ventureLoadHistory(),250);};
 $('ventureSettingsToggle').onclick=()=>ventureTogglePopover('settings');$('ventureSettingsClose').onclick=()=>ventureClosePopover('settings');$('ventureAvatar').onclick=()=>ventureTogglePopover('account');$('ventureAccountClose').onclick=()=>ventureClosePopover('account');
 $('ventureSettings').addEventListener('input',ventureChangedSettings);$('ventureSettings').addEventListener('change',ventureChangedSettings);['pointermove','keydown','focusin','focusout'].forEach(type=>$('ventureSettings').addEventListener(type,ventureSettingsIdle));
 $('ventureSettings').addEventListener('pointerdown',()=>{venture.dragging=true;ventureSettingsIdle();});document.addEventListener('pointerup',()=>{venture.dragging=false;ventureSettingsIdle();});
 $('ventureCompose').onsubmit=event=>{event.preventDefault();void ventureSend();};$('ventureAttach').onclick=()=>$('ventureFileInput').click();$('ventureFileInput').onchange=event=>{ventureAddFiles(event.target.files);event.target.value='';};$('ventureStop').onclick=()=>void ventureCancel();
 $('ventureMessage').oninput=()=>{if(ventureRecording?.phase==='awaiting-space')ventureInsertDictation(ventureRecording);ventureResizeComposer();if(venture.current)venture.drafts.set(venture.current.id,$('ventureMessage').value);};
 $('ventureMessage').onkeydown=event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing&&matchMedia('(pointer:fine)').matches){event.preventDefault();$('ventureCompose').requestSubmit();}};
 $('ventureCompose').addEventListener('paste',event=>{if(event.clipboardData?.files.length){ventureAddFiles(event.clipboardData.files);event.preventDefault();}});
 for(const type of ['dragenter','dragover'])root.addEventListener(type,event=>{if(event.dataTransfer?.types.includes('Files')){event.preventDefault();$('ventureCompose').classList.add('drop-active');}});
 root.addEventListener('dragleave',event=>{if(!root.contains(event.relatedTarget))$('ventureCompose').classList.remove('drop-active');});root.addEventListener('drop',event=>{event.preventDefault();$('ventureCompose').classList.remove('drop-active');ventureAddFiles(event.dataTransfer?.files);});
 $('ventureAttachments').onclick=event=>{const button=event.target.closest('[data-remove]');if(button){venture.files.splice(Number(button.dataset.remove),1);venturePaintAttachments();}};
 $('ventureTurns').addEventListener('click',event=>void ventureTurnAction(event));$('ventureHistory').onclick=event=>{const rename=event.target.closest('[data-rename]'),item=event.target.closest('[data-conversation]');if(rename)ventureOpenRename(rename.dataset.rename);else if(item)void ventureSelect(item.dataset.conversation);};
 let press; $('ventureHistory').addEventListener('pointerdown',event=>{const row=event.target.closest('[data-conversation]');if(row&&event.pointerType!=='mouse')press=setTimeout(()=>ventureOpenRename(row.dataset.conversation),550);});for(const type of ['pointerup','pointercancel','pointermove'])$('ventureHistory').addEventListener(type,()=>clearTimeout(press));
 $('ventureHistory').oncontextmenu=event=>{const row=event.target.closest('[data-conversation]');if(row){event.preventDefault();ventureOpenRename(row.dataset.conversation);}};
 $('ventureDeleteConversation').onclick=()=>void ventureDeleteConversation();
 $('ventureChooseAvatar').onclick=()=>$('ventureAvatarInput').click();$('ventureAvatarInput').onchange=event=>{void ventureUploadAvatar(event.target.files[0]);event.target.value='';};$('ventureRemoveAvatar').onclick=()=>void ventureRemoveAvatar();$('ventureShowStorage').onclick=()=>void ventureShowStorage();
 $('ventureRenameCancel').onclick=()=>$('ventureRenameDialog').close();$('ventureRenameForm').onsubmit=event=>{event.preventDefault();void ventureSaveRename();};
 $('ventureSaveKey').onclick=()=>void ventureSaveKey();$('ventureRemoveKey').onclick=()=>void ventureRemoveKey();$('ventureConnection').onclick=()=>{ventureClosePopover('account');openCloudSettings();};$('ventureSignOut').onclick=()=>void accountGoogleSignOut();
 $('ventureCheck').onclick=()=>{if(venture.pending?.form)void venturePostPending();else void venturePoll(true);};$('ventureMic').onclick=ventureDictate;
 window.addEventListener('beforeunload',event=>{if(ventureRecording&&ventureDictationAudio(ventureRecording)){event.preventDefault();event.returnValue='';}});
 window.addEventListener('pagehide',()=>ventureStopDictation());
 document.addEventListener('pointerdown',event=>{for(const kind of ['settings','account']){const panel=$('venture'+(kind==='settings'?'Settings':'Account')),button=$('venture'+(kind==='settings'?'SettingsToggle':'Avatar'));if(!panel.hidden&&!panel.contains(event.target)&&!button.contains(event.target))ventureClosePopover(kind,false);}});
 root.addEventListener('keydown',event=>{if(event.key==='Escape'){ventureClosePopover('settings');ventureClosePopover('account');if(matchMedia('(max-width:760px)').matches)ventureSidebar(false);}});
 window.addEventListener('online',()=>{if(venture.open)void venturePoll(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden)ventureStopDictation(false);else if(venture.open)void venturePoll(true);});
 if(window.visualViewport){const size=()=>{if(venture.open&&matchMedia('(max-width:760px)').matches){root.style.height=visualViewport.height+'px';root.style.top=visualViewport.offsetTop+'px';}else{root.style.height='';root.style.top='';}};visualViewport.addEventListener('resize',size);visualViewport.addEventListener('scroll',size);window.addEventListener('resize',size);venture.viewport=size;}
}
function ventureSidebar(open){$('visionVenture').classList.toggle('history-open',open);$('ventureHistoryToggle').setAttribute('aria-expanded',String(open));const mobile=matchMedia('(max-width:760px)').matches;$('ventureScrim').hidden=!open||!mobile;$('ventureSidebar').inert=!open;$('visionVenture').querySelector('.venture-main').inert=mobile&&open;}
function ventureIdentity(){
 const uid=ventureScope();if(uid===venture.uid)return;
 venture.epoch++;venture.selection++;venture.uid=uid;venture.ready=false;venture.current=null;venture.runs=[];venture.history=[];venture.files=[];venture.drafts.clear();venture.pending=null;venture.calibration=null;venture.funding=null;venture.models=null;venture.modelsLoading=false;venture.modelNotice='';venture.fundingReturn=null;venture.sending=false;venture.polling=false;venture.cursor=0;venture.settings=ventureSettings();venture.rendered.clear();ventureResetAvatar();$('ventureAvatarStatus').textContent='Photos are automatically cropped and compressed.';$('ventureStoragePath').textContent='';$('ventureStorageDetails').hidden=true;clearTimeout(venture.poll);clearTimeout(venture.settingsSaving);ventureStopDictation();
 $('ventureTurns')?.replaceChildren();$('ventureHistory')?.replaceChildren();$('ventureMessage').value='';$('ventureKey').value='';$('ventureSearch').value='';$('ventureAttachments').replaceChildren();$('ventureBalanceDialog').close();$('ventureRenameDialog').close();consoleClosePreview();ventureClose();
}
const venturePreviousAccountGate=accountUpdateGate;
accountUpdateGate=function(){venturePreviousAccountGate();if($('visionVenture'))ventureIdentity();};
const ventureLegacyOpen=openVisionConsole;
openVisionConsole=function(){if(typeof trialActive==='function'&&trialActive()){ventureLegacyOpen();return;}void ventureOpen();};
const ventureLegacyArtifact=consoleArtifactBlob;
consoleArtifactBlob=async function(file,run){if(!run.ventureId)return ventureLegacyArtifact(file,run);const epoch=venture.epoch;const response=await ventureFetch(ventureRunPath(run.ventureId)+'/'+encodeURIComponent(run.runId)+'/artifacts/'+encodeURIComponent(file.id));const blob=await response.blob();if(epoch!==venture.epoch)throw new Error('Account changed while downloading.');return blob;};
async function ventureOpen(){
 ventureIdentity();if(!venture.uid){openAccountDialog('Sign in to open Venture.');return;}
 venture.open=true;venture.ready=false;$('visionConsole').hidden=true;$('visionVenture').hidden=false;ventureSidebar(matchMedia('(min-width:761px)').matches);venture.viewport?.();venturePaintAccount();ventureSetNotice('');const epoch=venture.epoch;
 try{const health=await ventureJSON('/health');if(epoch!==venture.epoch)return;if(!health.capabilities?.ventureV2)throw new Error('Venture needs the new FUPCJ Server update. Your existing board and saved projects are unchanged.');
 const prefs=await ventureJSON('/venture/preferences');if(epoch!==venture.epoch)return;venture.settings=ventureSettings(prefs.settings);venturePaintSettings();void ventureLoadModels();await ventureLoadHistory();
 const saved=venture.current?.id||ventureRecall('selection');if(saved)await ventureSelect(saved);else ventureBlank();if(epoch!==venture.epoch)return;venture.ready=true;venturePaintStatus();void ventureLoadFunding();void ventureLoadProfile();venture.fundingReturn=ventureRecall('funding-return');void ventureResumeFunding();
 }catch(error){if(epoch===venture.epoch){ventureSetNotice(ventureError(error));venturePaintStatus();}}
}
function ventureClose(){venture.open=false;clearTimeout(venture.poll);ventureStopDictation();ventureClosePopover('settings',false);ventureClosePopover('account',false);if($('visionVenture')){$('visionVenture').hidden=true;$('visionVenture').querySelector('.venture-main').inert=false;}$('ventureKey').value='';}
function ventureBlank(){venture.current=null;venture.runs=[];venture.cursor=0;venture.files=[];venture.messageCursor=null;venture.pending=null;venture.rendered.clear();$('ventureTurns').replaceChildren();$('ventureMessage').value='';venturePaint();ventureSchedule(6000);}
async function ventureNew(){
 if(!venture.ready){ventureSetNotice('Reconnect to the updated FUPCJ Server before starting a venture.');return;}
 if(venture.sending){ventureSetNotice('Wait for the upload to be accepted before switching conversations.');return;}
 ++venture.selection;ventureStopDictation();clearTimeout(venture.poll);if(venture.current)venture.drafts.set(venture.current.id,$('ventureMessage').value);ventureRemember('selection',null);ventureBlank();ventureSetNotice('');if(matchMedia('(max-width:760px)').matches)ventureSidebar(false);$('ventureMessage').focus({preventScroll:true});
}
async function ventureLoadHistory(more=false,refresh=false){
 const epoch=venture.epoch,query=$('ventureSearch').value,params=new URLSearchParams();if(query)params.set('q',query);if(more&&venture.historyCursor)params.set('before',venture.historyCursor);
 try{const value=await ventureJSON('/venture/conversations'+(params.size?'?'+params:''));if(epoch!==venture.epoch||query!==$('ventureSearch').value)return;const keepOlder=refresh&&venture.history.length>50,tail=keepOlder?venture.history.filter(c=>!value.conversations.some(n=>n.id===c.id)&&c.updatedAt<=(value.conversations.at(-1)?.updatedAt||0)):[];venture.history=more?[...venture.history,...value.conversations.filter(c=>!venture.history.some(old=>old.id===c.id))]:[...value.conversations,...tail];if(!keepOlder)venture.historyCursor=value.nextCursor;venture.lastHistoryLoad=Date.now();venturePaintHistory();}catch(error){if(epoch===venture.epoch)ventureSetNotice(ventureError(error));}
}
async function ventureSelect(cid){
 if(venture.sending)return;
 const serial=++venture.selection;ventureStopDictation();if(venture.current)venture.drafts.set(venture.current.id,$('ventureMessage').value);ventureClosePopover('settings',false);clearTimeout(venture.poll);ventureSetNotice('');
 try{const value=await ventureJSON(venturePath(cid));if(serial!==venture.selection)return;venture.current=value.conversation;venture.runs=value.runs.map(r=>({...r,ventureId:cid}));venture.cursor=value.cursor;venture.messageCursor=value.nextCursor;venture.settings=ventureSettings(value.conversation.settings);venture.files=[];venture.pending=ventureRecall('pending-'+cid);venture.rendered.clear();$('ventureTurns').replaceChildren();$('ventureMessage').value=venture.drafts.get(cid)||'';ventureRemember('selection',cid);venturePaintSettings();ventureResolvePending();venturePaint();$('ventureTranscript').scrollTop=$('ventureTranscript').scrollHeight;if(matchMedia('(max-width:760px)').matches)ventureSidebar(false);ventureSchedule(1200);
 }catch(error){if(serial===venture.selection){if(error.status===404||error.status===410){ventureRemember('selection',null);ventureBlank();void ventureLoadHistory();}ventureSetNotice(ventureError(error));venturePaintStatus();}}
}
function ventureResolvePending(){if(!venture.pending)return;const found=venture.runs.find(r=>r.clientRequestId===venture.pending.clientRequestId);if(found){ventureRemember('pending-'+venture.current.id,null);venture.pending=null;venture.files=[];$('ventureMessage').value='';venture.drafts.delete(venture.current.id);venturePaintAttachments();}}
function ventureSchedule(ms){clearTimeout(venture.poll);if(venture.open)venture.poll=setTimeout(()=>void venturePoll(),document.hidden?15000:ms);}
async function venturePoll(force=false){
 if(!venture.open)return;if(venture.polling){ventureSchedule(1500);return;}if(!venture.current){await ventureLoadHistory(false,true);ventureSchedule(6000);return;}const cid=venture.current.id,serial=venture.selection;venture.polling=true;
 try{const data=await ventureJSON(venturePath(cid)+'?since='+encodeURIComponent(force?0:venture.cursor));if(serial!==venture.selection)return;const before=venture.runs.filter(r=>VENTURE_TERMINAL.has(r.status)).length,hadReply=venture.runs.some(r=>r.text?.trim()||r.artifacts?.length);
 for(const raw of data.runs){const run={...raw,ventureId:cid},index=venture.runs.findIndex(r=>r.runId===run.runId);if(index<0)venture.runs.push(run);else venture.runs[index]=run;}venture.runs.sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.runId.localeCompare(b.runId));venture.current=data.conversation;venture.cursor=data.cursor;ventureResolvePending();ventureSetNotice(data.conversation.storageWarning||'');venturePaint();
 if(before!==venture.runs.filter(r=>VENTURE_TERMINAL.has(r.status)).length||hadReply!==venture.runs.some(r=>r.text?.trim()||r.artifacts?.length)){void ventureLoadFunding();void ventureLoadHistory(false,true);}else if(Date.now()-(venture.lastHistoryLoad||0)>6000)void ventureLoadHistory(false,true);
 }catch(error){if(serial===venture.selection){if(error.status===404||error.status===410){ventureRemember('selection',null);ventureBlank();void ventureLoadHistory();}ventureSetNotice(ventureError(error));venturePaintStatus();}}finally{venture.polling=false;ventureSchedule(venture.runs.some(ventureActive)||venture.pending?1200:6000);}
}
async function ventureLoadOlder(){if(!venture.messageCursor)return;const serial=venture.selection,target=$('ventureTranscript'),oldHeight=target.scrollHeight;try{const data=await ventureJSON(venturePath()+'?before='+encodeURIComponent(venture.messageCursor));if(serial!==venture.selection)return;venture.runs=[...data.runs.filter(r=>!venture.runs.some(old=>old.runId===r.runId)).map(r=>({...r,ventureId:venture.current.id})),...venture.runs];venture.messageCursor=data.nextCursor;venturePaint();target.scrollTop+=target.scrollHeight-oldHeight;}catch(error){ventureSetNotice(ventureError(error));}}
const VENTURE_CHAT_ICONS={plane:'m12 3 2 7 7 4v2l-7-2v5l2 2H8l2-2v-5l-7 2v-2l7-4z',code:'m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18',music:'M9 18V5l11-2v13M9 8l11-2M9 18a3 2 0 1 1-6 0 3 2 0 0 1 6 0m11-2a3 2 0 1 1-6 0 3 2 0 0 1 6 0',image:'M3 3h18v18H3zM3 17l6-7 5 6 3-3 4 4M16 7h.01',repair:'m14 4-3 3 1 5-9 9-2-2 9-9-1-5 3-3',science:'M9 3h6M10 3v6L4 19v2h16v-2L14 9V3M7 15h10',food:'M5 3v7m3-7v7M2 3v7l3 3v8M17 3v18M17 3c-5 3-5 9 0 9',conversation:'M3 3h18v14H9l-6 4z'};
function ventureChatGraphic(value){if(value==='document')return ventureIcon('file');if(value==='travel')return ventureIcon('compass');return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="'+(VENTURE_CHAT_ICONS[value]||VENTURE_CHAT_ICONS.conversation)+'"/></svg>';}
function venturePaintHistory(){
 const host=$('ventureHistory'),signature=JSON.stringify([venture.current?.id,venture.historyCursor,$('ventureSearch').value,venture.history.map(c=>[c.id,c.title,c.graphic])]);if(host.dataset.signature===signature&&host.childElementCount)return;host.dataset.signature=signature;const scroll=host.scrollTop;host.replaceChildren();if(!venture.history.length){const p=document.createElement('p');p.className='venture-history-empty';p.textContent=$('ventureSearch').value?'No matching conversations.':'Your adventures will appear here.';host.appendChild(p);}
 for(const item of venture.history){const row=document.createElement('div');row.className='venture-history-row'+(venture.current?.id===item.id?' selected':'');row.dataset.conversation=item.id;const button=document.createElement('button');button.className='venture-history-open';button.dataset.conversation=item.id;const graphic=document.createElement('span');graphic.className='venture-history-graphic';graphic.setAttribute('aria-hidden','true');graphic.innerHTML=ventureChatGraphic(item.graphic);const title=document.createElement('span');title.className='venture-history-title';title.textContent=item.title;button.append(graphic,title);button.title=item.title;button.setAttribute('aria-current',venture.current?.id===item.id?'page':'false');const rename=document.createElement('button');rename.className='v-icon venture-rename';rename.dataset.rename=item.id;rename.title='Conversation options';rename.setAttribute('aria-label','Options for '+item.title);rename.innerHTML=ventureIcon('dots');row.append(button,rename);host.appendChild(row);}$('ventureMoreHistory').hidden=!venture.historyCursor;host.scrollTop=scroll;
}
function venturePaint(){
 $('ventureTitle').textContent=venture.current?.title||'Venture';$('ventureOlder').hidden=!venture.messageCursor;venturePaintHistory();venturePaintTurns();venturePaintStatus();venturePaintAttachments();ventureResizeComposer();
}
function ventureTurnHTML(run,index){
 const uploads=(run.attachments||[]).map((f,i)=>'<button class="venture-upload" data-v-action="upload" data-file="'+i+'">'+ventureIcon('file')+escapeHTML(f.name)+'</button>').join('');
 const artifacts=(run.artifacts||[]).map((file,i)=>'<div class="venture-file-card"><button data-v-action="preview" data-file="'+i+'" '+(!file.ready?'disabled':'')+'>'+ventureIcon('file')+'<span>'+escapeHTML(file.name)+'<small>'+(file.error?escapeHTML(file.error):file.ready?'Saved on FUPCJ Server':'Saving file…')+'</small></span></button><button class="v-icon" data-v-action="download" data-file="'+i+'" aria-label="Download '+escapeHTML(file.name)+'" '+(!file.ready?'disabled':'')+'>'+ventureIcon('download')+'</button></div>').join('');
 const text=run.text?consoleMarkdown(run.text,run,index):'<p class="venture-placeholder">'+(ventureActive(run)?'Working on it…':run.status==='cancelled'?'Stopped.':'No response text.')+'</p>';
 return '<div class="venture-user"><div>'+escapeHTML(run.message||'Use the attached project.')+'</div>'+(uploads?'<div class="venture-sent-uploads">'+uploads+'</div>':'')+'</div><div class="venture-assistant console-assistant-message"><div class="venture-response-meta">'+ventureModelBadge(run.model,run.runOptions?.mode)+(run.retryOf?' <span>Regenerated response</span>':'')+'</div>'+text+consoleSourceLinks(run)+(run.memorySources?.length?'<details class="venture-memory-sources"><summary>Context from past conversations</summary><p>'+run.memorySources.map(x=>escapeHTML(x.title)).join(' · ')+'</p></details>':'')+(artifacts?'<div class="venture-file-grid">'+artifacts+'</div>':'')+(run.preparationNotes?.length?'<details class="venture-preparation"><summary>File preparation notes</summary><p>'+escapeHTML(run.preparationNotes.join('\n'))+'</p></details>':'')+(run.error?'<p class="venture-error">'+escapeHTML(run.error)+'</p>':'')+'<div class="venture-response-actions"><button class="v-icon" data-v-action="copy" title="Copy response" aria-label="Copy response" '+(!run.text?'disabled':'')+'>'+ventureIcon('copy')+'</button><button class="v-icon" data-v-action="retry" title="Regenerate response (uses API credits)" aria-label="Regenerate response" '+(ventureActive(run)?'disabled':'')+'>'+ventureIcon('retry')+'</button><span>'+(!ventureActive(run)?run.status==='completed'?'':escapeHTML(run.status):escapeHTML(run.phase||'Working'))+'</span></div></div>';
}
function venturePaintTurns(){
 const scroll=$('ventureTranscript'),bottom=scroll.scrollHeight-scroll.scrollTop-scroll.clientHeight<120,host=$('ventureTurns');
 if(!venture.runs.length){if(!host.querySelector('.venture-welcome'))host.innerHTML='<div class="venture-welcome"><div class="venture-welcome-mark">'+ventureBrandIcon()+'</div><span>VENTURE</span><h1>Where will you venture?</h1><p>Ask a question. Bring your files.<br>Pick up where you left off.</p><div class="venture-welcome-chips"><button data-v-action="attach">'+ventureIcon('plus')+' Bring your files</button><button data-v-action="board">Use your Vision board</button></div></div>';return;}
 host.querySelector('.venture-welcome')?.remove();for(const [index,run] of venture.runs.entries()){let article=host.querySelector('[data-venture-run="'+CSS.escape(run.runId)+'"]');if(!article){article=document.createElement('article');article.className='venture-turn';article.dataset.ventureRun=run.runId;const next=venture.runs[index+1];const nextNode=next&&host.querySelector('[data-venture-run="'+CSS.escape(next.runId)+'"]');host.insertBefore(article,nextNode||null);}const signature=JSON.stringify([run.sequence,run.status,run.text,run.artifacts,run.error,run.preparationNotes,run.memorySources,run.memoryEnabled,index]);if(venture.rendered.get(run.runId)!==signature){article.innerHTML=ventureTurnHTML(run,index);venture.rendered.set(run.runId,signature);}}
 if(bottom)scroll.scrollTop=scroll.scrollHeight;
}
function venturePaintStatus(){
 const active=venture.runs.find(ventureActive),pending=!!venture.pending;$('ventureSend').hidden=!!active&&!venture.sending;$('ventureStop').hidden=!active||venture.sending;$('ventureSend').disabled=!venture.ready||venture.sending||pending||!!active||ventureDictationBusy();
 $('ventureActivity').textContent=venture.sending?'Uploading. Keep this page open until accepted…':pending?'Confirming submission. No duplicate request has been sent.':active?(active.phase||'Thinking…'):venture.notice?'Connection needs attention.':'Ready when you are.';$('ventureActivity').classList.toggle('working',!!active||venture.sending);
 $('ventureCheck').hidden=!venture.notice&&!pending;$('ventureCheck').textContent=pending?.form?'Retry same submission':venture.pending?.form?'Retry same submission':'Check connection';$('ventureCheck').disabled=venture.sending;
 $('ventureFootnote').textContent=venture.sending?'Uploads must finish before you close this page.':active?'FUPCJ Server is working. You can close Vision and return later.':'Accepted requests keep working when you leave.';
 $('ventureToolsLabel').textContent=venture.settings.runOptions.codeInterpreter?'Code & files ready':'Text only';
}
function venturePaintAttachments(){const host=$('ventureAttachments');host.innerHTML=venture.files.map((file,index)=>'<span class="venture-attachment">'+ventureIcon('file')+'<span>'+escapeHTML(file.name)+'</span><button type="button" data-remove="'+index+'" aria-label="Remove '+escapeHTML(file.name)+'">×</button></span>').join('');}
function ventureAddFiles(files){if(venture.sending||venture.pending){ventureSetNotice('Finish or check the current submission before changing attachments.');return;}let total=venture.files.reduce((sum,f)=>sum+f.size,0);for(const file of Array.from(files||[])){if(venture.files.length>=20||total+file.size>128*1024*1024){ventureSetNotice('Attach up to 20 files and 128 MB total per message.');break;}venture.files.push(file);total+=file.size;}venturePaintAttachments();}
function ventureResizeComposer(){const field=$('ventureMessage');field.style.height='auto';field.style.height=Math.min(field.scrollHeight,Math.max(100,window.innerHeight*.25))+'px';}
async function ventureSend(retry=null){
 if(venture.sending||venture.pending||venture.runs.some(ventureActive)||!venture.ready||ventureDictationBusy())return;const message=retry?retry.message:$('ventureMessage').value.trim(),files=retry?[]:venture.files.slice(),board=!retry&&$('ventureIncludeBoard').checked;
 if(!message&&!files.length&&!board)return;if((files.length||board||retry?.attachments.length)&&!venture.settings.runOptions.codeInterpreter){ventureSetNotice('Enable Code & files before attaching files or the board.');return;}
 const epoch=venture.epoch;venture.sending=true;ventureSetNotice('');venturePaintStatus();
 try{if(!venture.current){const data=await ventureJSON('/venture/conversations','POST',{id:ventureId(),settings:venture.settings});if(epoch!==venture.epoch)return;venture.current=data.conversation;ventureRemember('selection',venture.current.id);}
 const cid=venture.current.id,form=new FormData();let projectPrompt=retry?.projectPrompt||'';
 if(board){const bundle=await consoleBoardFiles();if(epoch!==venture.epoch)return;const entries={};for(const file of bundle)entries[file.name]=typeof file.data==='string'?new TextEncoder().encode(file.data):new Uint8Array(await file.data.arrayBuffer());projectPrompt=typeof bundle.find(f=>f.name==='MAIN_PROMPT.txt')?.data==='string'?bundle.find(f=>f.name==='MAIN_PROMPT.txt').data:await consoleFileText(bundle.find(f=>f.name==='MAIN_PROMPT.txt'));const zip=window.fflate.zipSync(entries,{level:6});form.append('file',new Blob([zip],{type:'application/zip'}),'vision-board.zip');if(zip.byteLength+files.reduce((sum,f)=>sum+f.size,0)>128*1024*1024)throw new Error('The board and attachments exceed the 128 MB message limit.');}
 for(const file of files)form.append('attachments',file,file.name);
 const options={clientRequestId:ventureId(),...venture.settings,message:message||(board?'Follow the instructions in the attached Vision board.':'Use the attached files.'),projectPrompt,previousRunId:retry?retry.previousRunId||null:venture.runs.at(-1)?.runId||null,...(retry?{retryOf:retry.runId}:{})};form.append('options',JSON.stringify(options));
 venture.pending={clientRequestId:options.clientRequestId,cid,form};ventureRemember('pending-'+cid,{clientRequestId:options.clientRequestId,cid});await venturePostPending();
 }catch(error){if(epoch===venture.epoch)ventureSetNotice(ventureError(error));}finally{if(epoch===venture.epoch){venture.sending=false;venturePaintStatus();ventureSchedule(1000);}}
}
async function venturePostPending(){
 const pending=venture.pending;if(!pending?.form)return;const epoch=venture.epoch;venture.sending=true;venturePaintStatus();
 try{const response=await ventureFetch(ventureRunPath(pending.cid),{method:'POST',body:pending.form});const run=await response.json();if(epoch!==venture.epoch||pending!==venture.pending)return;const i=venture.runs.findIndex(r=>r.runId===run.runId);if(i<0)venture.runs.push({...run,ventureId:pending.cid});ventureResolvePending();ventureSetNotice('');venturePaint();void ventureLoadHistory();
 }catch(error){if(epoch!==venture.epoch)return;if(error.status&&error.status<500&&error.status!==408){ventureRemember('pending-'+pending.cid,null);venture.pending=null;}ventureSetNotice(ventureError(error)+(venture.pending?' Use “Retry same submission” to reconnect with the same request ID.':''));}finally{if(epoch===venture.epoch){venture.sending=false;venturePaintStatus();ventureSchedule(1000);}}
}
async function ventureCancel(){const run=venture.runs.find(ventureActive);if(!run)return;try{await ventureJSON(ventureRunPath()+'/'+encodeURIComponent(run.runId)+'/cancel','POST',{});await venturePoll(true);}catch(error){ventureSetNotice(ventureError(error));}}
async function ventureTurnAction(event){
 const button=event.target.closest('button');if(!button)return;const action=button.dataset.vAction||button.dataset.consoleAction;
 if(action==='attach'){$('ventureFileInput').click();return;}if(action==='board'){$('ventureIncludeBoard').checked=true;$('ventureMessage').focus();return;}
 const article=button.closest('[data-venture-run]'),run=venture.runs.find(r=>r.runId===article?.dataset.ventureRun);if(!run)return;const index=Number(button.dataset.file??button.dataset.artifact);
 button.disabled=true;try{if(action==='copy')await consoleCopyText(run.text);else if(action==='retry'){if(!confirm('Generate another response to this message? The original stays saved. This uses API credits.'))return;await ventureSend(run);}else if(action==='preview')await consolePreviewArtifact(run,index);else if(action==='download'){const file=run.artifacts[index];download(await consoleArtifactBlob(file,run),R.safeFilename(file.name));}else if(action==='upload'){const response=await ventureFetch(venturePath(run.ventureId)+'/uploads/'+encodeURIComponent(run.runId)+'/'+index);download(await response.blob(),R.safeFilename(run.attachments[index].name));}}catch(error){ventureSetNotice(ventureError(error));}finally{button.disabled=false;}
}
function ventureEfforts(){return ventureParameterProfile()?.efforts||['auto'];}
function ventureChoiceLabel(value){return ({auto:'Model default',xhigh:'Extra high',max:'Maximum'})[value]||value[0].toUpperCase()+value.slice(1);}
// Current GPT-5.6/GPT-6 families expose 128K; the older catalog remains capped at 64K.
function ventureModelTokenLimit(model=venture.settings.model){return ventureParameterLimit(model);}
function venturePaintSettings(){const s=venture.settings,maxTokens=ventureModelTokenLimit(s.model),tokens=Math.max(512,Math.min(maxTokens,Number(s.maxOutputTokens)||VENTURE_DEFAULTS.maxOutputTokens));s.maxOutputTokens=tokens;venturePaintModelPicker();$('ventureMaxTokens').max=maxTokens;$('ventureMaxTokens').value=tokens;$('ventureMaxTokensEnd').textContent=maxTokens.toLocaleString();venturePaintParameterDetails();$('ventureWeb').checked=s.runOptions.webSearch;$('ventureCode').checked=s.runOptions.codeInterpreter;$('ventureMemory').checked=s.memoryEnabled;const efforts=ventureEfforts();$('ventureEffort').max=efforts.length-1;$('ventureEffort').value=Math.max(0,efforts.indexOf(s.runOptions.effort));$('ventureVerbosity').value=['auto','low','medium','high'].indexOf(s.runOptions.verbosity);venturePaintDials();}
function venturePaintDials(){const effort=ventureEfforts()[Number($('ventureEffort').value)]||'auto',verbosity=['auto','low','medium','high'][Number($('ventureVerbosity').value)],maxTokens=ventureModelTokenLimit(),tokens=Math.max(512,Math.min(maxTokens,Number($('ventureMaxTokens').value)||VENTURE_DEFAULTS.maxOutputTokens)),tokenLabel=tokens.toLocaleString();$('ventureEffortValue').textContent=ventureChoiceLabel(effort);$('ventureVerbosityValue').textContent=ventureChoiceLabel(verbosity);$('ventureMaxTokensValue').textContent=tokenLabel;$('ventureEffort').setAttribute('aria-valuetext',ventureChoiceLabel(effort));$('ventureVerbosity').setAttribute('aria-valuetext',ventureChoiceLabel(verbosity));$('ventureMaxTokens').setAttribute('aria-valuetext',tokenLabel+' output tokens');}
function ventureChangedSettings(event){
 if(event.target.id==='ventureModel'){const choices=ventureEfforts();$('ventureEffort').max=choices.length-1;$('ventureEffort').value=Math.max(0,choices.indexOf(venture.settings.runOptions.effort));}
 venture.settings=ventureSettings({memoryEnabled:$('ventureMemory').checked,model:venture.settings.model,maxOutputTokens:Number($('ventureMaxTokens').value),runOptions:{mode:!ventureParameterProfile()?.pro?'auto':ventureModelIsAstra()?venture.settings.runOptions.mode:($('venturePro').checked?'pro':'auto'),effort:ventureEfforts()[Number($('ventureEffort').value)],verbosity:ventureParameterProfile()?.verbosity?['auto','low','medium','high'][Number($('ventureVerbosity').value)]:'auto',webSearch:$('ventureWeb').checked,codeInterpreter:$('ventureCode').checked}});venture.settingsVersion++;venturePaintModelPicker();venturePaintDials();venturePaintStatus();ventureSettingsIdle();clearTimeout(venture.settingsSaving);venture.settingsSaving=setTimeout(()=>void venturePersistSettings(),600);
}
async function venturePersistSettings(){
 if(venture.persisting){venture.persistAgain=true;return;}venture.persisting=true;try{await venturePersistOneSettings();}finally{venture.persisting=false;if(venture.persistAgain){venture.persistAgain=false;void venturePersistSettings();}}
}
async function venturePersistOneSettings(){
 const version=venture.settingsVersion,epoch=venture.epoch,cid=venture.current?.id,revision=venture.current?.revision,value=structuredClone(venture.settings),maxTokens=ventureModelTokenLimit(value.model);if(!/^[A-Za-z0-9_.:-]{1,100}$/.test(value.model)||value.maxOutputTokens<512||value.maxOutputTokens>maxTokens){$('ventureSettingsStatus').textContent='Choose a model and an output limit from 512 to '+maxTokens.toLocaleString()+'.';return;}
 try{await ventureJSON('/venture/preferences','PUT',value);if(cid){const data=await ventureJSON(venturePath(cid),'PATCH',{revision,settings:value});if(epoch===venture.epoch&&venture.current?.id===cid){venture.current.revision=data.conversation.revision;venture.current.settings=data.conversation.settings;}}if(epoch===venture.epoch&&version===venture.settingsVersion)$('ventureSettingsStatus').textContent='Saved for your account.';
 }catch(error){if(epoch===venture.epoch)$('ventureSettingsStatus').textContent=ventureError(error);}
}
function ventureSettingsIdle(){clearTimeout(venture.settingsTimer);}
function ventureTogglePopover(kind){const id=kind==='settings'?'ventureSettings':'ventureAccount',panel=$(id);if(!panel.hidden){ventureClosePopover(kind);return;}ventureClosePopover(kind==='settings'?'account':'settings',false);panel.hidden=false;$(kind==='settings'?'ventureSettingsToggle':'ventureAvatar').setAttribute('aria-expanded','true');panel.focus({preventScroll:true});if(kind==='settings'){venturePaintSettings();ventureSettingsIdle();}else{venturePaintAccount();void ventureLoadFunding();void ventureLoadProfile();}}
function ventureClosePopover(kind,restore=true){const panel=$(kind==='settings'?'ventureSettings':'ventureAccount');if(!panel)return;const wasOpen=!panel.hidden;panel.hidden=true;const button=$(kind==='settings'?'ventureSettingsToggle':'ventureAvatar');button.setAttribute('aria-expanded','false');if(kind==='settings'){clearTimeout(venture.settingsTimer);$('ventureModelsPanel').hidden=true;$('ventureModel').setAttribute('aria-expanded','false');}else $('ventureKey').value='';if(wasOpen&&restore&&venture.open)button.focus({preventScroll:true});}
function venturePaintAccount(){const user=accountFirebase?.currentUser,avatar=$('ventureAvatar');avatar.replaceChildren();const name=user?.displayName||user?.email?.split('@')[0]||'Vision account',initials=name.split(/\s+/).map(s=>s[0]).join('').slice(0,2).toUpperCase();avatar.textContent=initials;const photo=ventureAvatarObjectURL||user?.photoURL;if(photo){try{const url=new URL(photo);if(url.protocol==='https:'||(ventureAvatarObjectURL&&url.protocol==='blob:')){const image=document.createElement('img');image.alt='';image.referrerPolicy='no-referrer';image.src=url.href;image.onerror=()=>image.remove();avatar.appendChild(image);}}catch{}}$('ventureAccountName').textContent=name;$('ventureAccountEmail').textContent=user?.email||'';venturePaintFunding();}
async function ventureLoadFunding(){const epoch=venture.epoch;try{const data=await ventureJSON('/venture/funding');if(epoch===venture.epoch){venture.funding=data;venturePaintFunding();}}catch(error){if(epoch===venture.epoch){venture.funding=null;$('ventureFundingUpdated').textContent=ventureError(error);venturePaintFunding(false);}}}
function venturePaintFunding(update=true){const data=venture.funding,fraction=typeof data?.fraction==='number'?Math.max(0,Math.min(1,data.fraction)):null,battery=$('ventureBattery'),fill=$('ventureBatteryFill');battery.classList.toggle('unknown',fraction===null);battery.classList.toggle('empty',fraction===0);fill.style.width=(fraction===null?100:fraction*100)+'%';fill.style.background=fraction===null?'#58605b':fraction<=.2?'#ed7975':fraction<.55?'#d6c16c':'var(--accent)';if(fraction===null){battery.removeAttribute('aria-valuenow');battery.setAttribute('aria-valuetext','Balance unavailable');}else{battery.setAttribute('aria-valuenow',String(Math.round(fraction*100)));battery.setAttribute('aria-valuetext',data.status==='exhausted'?'OpenAI reports credits exhausted':'Estimated balance remaining '+Math.round(fraction*100)+' percent');}
 $('ventureFundingStatus').textContent=({available:'Available',low:'Running low','estimated-empty':'Estimate depleted',exhausted:'Credits exhausted',uncalibrated:'Not calibrated','no-key':'No saved API key'})[data?.status]||'Unavailable';if(update)$('ventureFundingUpdated').textContent=data?.updatedAt?'Updated '+new Date(data.updatedAt*1000).toLocaleString():data?.status==='no-key'?'Save your API key, then set a starting balance.':'Set a starting balance to activate the meter.';$('ventureFundingCoverage').textContent=(data?.issues?.length?data.issues.join(' ')+' ':'')+'Tracks Vision activity only. Other apps, credit expiry, refunds, or unreported charges can change the official balance.';
}
async function ventureSaveBalance(){
 const epoch=venture.epoch,form=$('ventureBalanceForm'),button=form.querySelector('[type=submit]'),kind=venture.balanceKind||'set',amount=$('ventureBalanceAmount').value;
 const same=venture.calibration&&venture.calibration.kind===kind&&venture.calibration.amount===amount;
 const body=same?venture.calibration:{requestId:ventureId(),kind,amount,revision:venture.funding?.revision||0,...(venture.balanceConnection?{connectionId:venture.balanceConnection}:{})};venture.calibration=body;button.disabled=true;
 try{const data=await ventureJSON('/venture/funding','POST',body);if(epoch!==venture.epoch)return;venture.calibration=null;venture.funding=data;venturePaintFunding();$('ventureBalanceDialog').close();ventureTogglePopover('account');}
 catch(error){if(epoch===venture.epoch){if(error.status===409||error.status===400)venture.calibration=null;$('ventureBalanceStatus').textContent=ventureError(error);await ventureLoadFunding();}}finally{button.disabled=false;}
}
async function ventureSaveKey(){const input=$('ventureKey'),value=input.value.trim();if(!value){$('ventureKeyStatus').textContent='Enter a normal OpenAI API key.';return;}const epoch=venture.epoch;$('ventureSaveKey').disabled=true;try{await ventureJSON('/account/openai-key','PUT',{apiKey:value});if(epoch!==venture.epoch)return;$('consoleKey').value=value;input.value='';$('ventureKeyStatus').textContent='Saved encrypted on FUPCJ Server. This connection has its own balance estimate.';venture.calibration=null;venture.models=null;await ventureLoadFunding();void ventureLoadModels(true);}catch(error){if(epoch===venture.epoch)$('ventureKeyStatus').textContent=ventureError(error);}finally{$('ventureSaveKey').disabled=false;}}
async function ventureRemoveKey(){if(!confirm('Remove this account’s saved OpenAI API key? Existing conversations and files stay saved.'))return;const epoch=venture.epoch;try{await ventureJSON('/account/openai-key','DELETE');if(epoch!==venture.epoch)return;$('consoleKey').value='';$('ventureKey').value='';$('ventureKeyStatus').textContent='Saved key removed.';venture.calibration=null;venture.models=null;await ventureLoadFunding();void ventureLoadModels(true);}catch(error){$('ventureKeyStatus').textContent=ventureError(error);}}
let ventureRenameTarget=null;
function ventureOpenRename(cid){const item=venture.history.find(c=>c.id===cid)||venture.current;if(!item)return;ventureRenameTarget={...item};$('ventureRenameValue').value=item.title;$('ventureRenameStatus').textContent='';$('ventureRenameDialog').showModal();$('ventureRenameValue').select();}
async function ventureSaveRename(){const item=ventureRenameTarget;if(!item)return;try{const data=await ventureJSON(venturePath(item.id),'PATCH',{revision:item.revision,title:$('ventureRenameValue').value.trim()});if(venture.current?.id===item.id){venture.current={...venture.current,...data.conversation};$('ventureTitle').textContent=data.conversation.title;}$('ventureRenameDialog').close();await ventureLoadHistory();}catch(error){$('ventureRenameStatus').textContent=ventureError(error);if(error.status===409){await ventureLoadHistory();ventureRenameTarget=venture.history.find(c=>c.id===item.id)||item;}}}
ventureInstall();$('runProjectBtn').onclick=openVisionConsole;
